import { ContentItem, Topic, Source } from "./types";

export const mockItems: ContentItem[] = [
  {
    id: "1",
    title: "The Rise of AI Agents in Enterprise Software",
    summary:
      "A comprehensive look at how AI agents are transforming enterprise workflows, from customer support to internal operations. Companies like Salesforce and Microsoft are leading the charge with autonomous agent frameworks that can handle multi-step tasks without human intervention.",
    fullContent:
      "AI agents represent a fundamental shift in how enterprise software works. Unlike traditional automation that follows rigid rules, AI agents can reason about tasks, break them into steps, and adapt when things don't go as planned...",
    sourceType: "linkedin",
    contentType: "article",
    topics: ["AI Agents", "Enterprise Software", "Automation"],
    author: "Sarah Chen",
    publication: "TechCrunch",
    url: "https://example.com/ai-agents-enterprise",
    priority: "high",
    isRead: false,
    createdAt: "2026-02-26T08:30:00Z",
  },
  {
    id: "2",
    title: "Understanding RAG Architecture Patterns",
    summary:
      "Deep dive into Retrieval Augmented Generation patterns, comparing naive RAG, advanced RAG with re-ranking, and modular RAG architectures. Includes performance benchmarks across different use cases.",
    sourceType: "slack",
    contentType: "article",
    topics: ["RAG", "AI Architecture", "LLMs"],
    author: "James Liu",
    publication: "Towards Data Science",
    url: "https://example.com/rag-patterns",
    priority: "high",
    isRead: false,
    createdAt: "2026-02-25T14:20:00Z",
  },
  {
    id: "3",
    title: "Andrej Karpathy: State of AI — Feb 2026",
    summary:
      "Karpathy discusses the convergence of reasoning models and tool-use, why multimodal models are finally production-ready, and his predictions for the next year of AI development.",
    sourceType: "twitter",
    contentType: "video",
    topics: ["AI", "Machine Learning", "Industry Trends"],
    author: "Andrej Karpathy",
    publication: "YouTube",
    url: "https://example.com/karpathy-state-of-ai",
    priority: "high",
    isRead: false,
    createdAt: "2026-02-25T10:00:00Z",
    duration: "47:32",
    thumbnailUrl: "/thumbnails/karpathy.jpg",
  },
  {
    id: "4",
    title: "India's Startup Ecosystem Hits $500B Valuation",
    summary:
      "The combined valuation of Indian startups has crossed the $500 billion mark, driven by fintech, AI, and SaaS sectors. The report highlights how Bangalore, Hyderabad, and Pune are emerging as global tech hubs.",
    sourceType: "gmail",
    contentType: "article",
    topics: ["Startups", "India Tech", "Venture Capital"],
    author: "Priya Sharma",
    publication: "Economic Times",
    url: "https://example.com/india-startups-500b",
    priority: "medium",
    isRead: false,
    createdAt: "2026-02-25T06:45:00Z",
  },
  {
    id: "6",
    title: "The Lex Fridman Podcast: Sam Altman on GPT-5",
    summary:
      "Sam Altman discusses OpenAI's roadmap, the challenges of scaling to GPT-5, safety research progress, and his vision for AGI. Altman also addresses concerns about AI regulation and the competitive landscape.",
    sourceType: "browser-extension",
    contentType: "podcast",
    topics: ["AI", "OpenAI", "AGI"],
    author: "Lex Fridman",
    publication: "Lex Fridman Podcast",
    url: "https://example.com/lex-sam-altman",
    priority: "medium",
    isRead: false,
    createdAt: "2026-02-24T12:00:00Z",
    duration: "2:34:18",
  },
  {
    id: "7",
    title: "TypeScript 6.0: What's New and Migration Guide",
    summary:
      "Complete overview of TypeScript 6.0 features including pattern matching, improved type inference, and the new module system. Includes a step-by-step migration guide from 5.x.",
    sourceType: "slack",
    contentType: "article",
    topics: ["TypeScript", "Developer Tools", "Programming"],
    author: "Daniel Rosenwasser",
    publication: "TypeScript Blog",
    url: "https://example.com/typescript-6",
    priority: "medium",
    isRead: true,
    createdAt: "2026-02-24T09:15:00Z",
  },
  {
    id: "8",
    title: "How Dream11 Scaled to 200M Users with Event-Driven Architecture",
    summary:
      "Engineering deep-dive into Dream11's migration from a monolithic architecture to event-driven microservices, handling 50M concurrent users during IPL peak.",
    sourceType: "linkedin",
    contentType: "article",
    topics: ["System Design", "Microservices", "Scale"],
    author: "Amit Kumar",
    publication: "InfoQ",
    url: "https://example.com/dream11-scale",
    priority: "high",
    isRead: false,
    createdAt: "2026-02-23T15:30:00Z",
  },
  {
    id: "9",
    title: "The Future of React: Server Components in Practice",
    summary:
      "Real-world case studies of companies adopting React Server Components. Performance improvements, developer experience lessons, and common pitfalls to avoid.",
    sourceType: "twitter",
    contentType: "article",
    topics: ["React", "Web Development", "Frontend"],
    author: "Dan Abramov",
    publication: "Overreacted",
    url: "https://example.com/rsc-practice",
    priority: "low",
    isRead: true,
    createdAt: "2026-02-23T11:00:00Z",
  },
  {
    id: "10",
    title: "Fireship: 10 AI Tools That Actually Ship Products",
    summary:
      "Quick-fire review of 10 AI-powered developer tools that go beyond hype — from code generation to automated testing to deployment optimization.",
    sourceType: "manual",
    contentType: "video",
    topics: ["AI Tools", "Developer Tools", "Productivity"],
    author: "Jeff Delaney",
    publication: "Fireship",
    url: "https://example.com/fireship-ai-tools",
    priority: "low",
    isRead: false,
    createdAt: "2026-02-23T08:00:00Z",
    duration: "12:04",
  },
  {
    id: "11",
    title: "Why Vector Databases Are Overrated for RAG",
    summary:
      "A contrarian take arguing that traditional search with BM25 + simple re-ranking outperforms vector databases for most RAG use cases, with benchmarks to back it up.",
    sourceType: "gmail",
    contentType: "article",
    topics: ["RAG", "Databases", "AI Architecture"],
    author: "Ben Clavié",
    publication: "Personal Blog",
    url: "https://example.com/vector-db-overrated",
    priority: "medium",
    isRead: false,
    createdAt: "2026-02-22T20:00:00Z",
  },
  {
    id: "13",
    title: "Claude's Extended Thinking: A Developer's Guide",
    summary:
      "Hands-on guide to leveraging Claude's extended thinking feature for complex reasoning tasks. Covers prompt engineering strategies, budget tokens, and when to use thinking vs standard mode.",
    sourceType: "browser-extension",
    contentType: "article",
    topics: ["Claude", "AI", "Developer Tools"],
    author: "Anthropic Team",
    publication: "Anthropic Docs",
    url: "https://example.com/claude-thinking-guide",
    priority: "high",
    isRead: false,
    createdAt: "2026-02-22T09:00:00Z",
  },
  {
    id: "14",
    title: "My First Million Podcast: Building in the AI Era",
    summary:
      "Sam Parr and Shaan Puri discuss business opportunities in the AI era, interview founders making $1M+ ARR with AI products, and debate whether AI will replace agencies.",
    sourceType: "manual",
    contentType: "podcast",
    topics: ["Business", "AI", "Entrepreneurship"],
    author: "Sam Parr & Shaan Puri",
    publication: "My First Million",
    url: "https://example.com/mfm-ai-era",
    priority: "low",
    isRead: false,
    createdAt: "2026-02-21T16:00:00Z",
    duration: "1:12:45",
  },
  {
    id: "15",
    title: "Kubernetes 2.0: The Complete Redesign",
    summary:
      "After years of incremental changes, Kubernetes 2.0 introduces a simplified API, native service mesh, and dramatically reduced resource overhead. Here's what changes for operators and developers.",
    sourceType: "slack",
    contentType: "article",
    topics: ["Kubernetes", "DevOps", "Infrastructure"],
    author: "Kelsey Hightower",
    publication: "CNCF Blog",
    url: "https://example.com/k8s-2",
    priority: "medium",
    isRead: false,
    createdAt: "2026-02-21T10:00:00Z",
  },
];

export const mockTopics: Topic[] = [
  { id: "1", name: "AI Agents", itemCount: 8, isActive: true, color: "#8B5CF6" },
  { id: "2", name: "RAG", itemCount: 5, isActive: true, color: "#06B6D4" },
  { id: "3", name: "System Design", itemCount: 4, isActive: true, color: "#F59E0B" },
  { id: "4", name: "Web Development", itemCount: 6, isActive: true, color: "#10B981" },
  { id: "5", name: "Startups", itemCount: 3, isActive: true, color: "#EF4444" },
  { id: "6", name: "Developer Tools", itemCount: 7, isActive: true, color: "#3B82F6" },
  { id: "7", name: "Cricket", itemCount: 2, isActive: true, color: "#84CC16" },
  { id: "8", name: "Machine Learning", itemCount: 9, isActive: true, color: "#EC4899" },
  { id: "9", name: "DevOps", itemCount: 3, isActive: false, color: "#6366F1" },
  { id: "10", name: "Business", itemCount: 4, isActive: true, color: "#F97316" },
];

export const mockSources: Source[] = [
  {
    id: "1",
    type: "gmail",
    name: "Gmail",
    isConnected: true,
    lastSynced: "2026-02-26T08:00:00Z",
    itemCount: 24,
    icon: "Mail",
  },
  {
    id: "2",
    type: "slack",
    name: "Slack",
    isConnected: true,
    lastSynced: "2026-02-26T08:15:00Z",
    itemCount: 31,
    icon: "Hash",
  },
  {
    id: "4",
    type: "twitter",
    name: "Twitter / X",
    isConnected: true,
    lastSynced: "2026-02-26T08:30:00Z",
    itemCount: 45,
    icon: "Twitter",
  },
  {
    id: "5",
    type: "linkedin",
    name: "LinkedIn",
    isConnected: false,
    itemCount: 0,
    icon: "Linkedin",
  },
  {
    id: "6",
    type: "browser-extension",
    name: "Browser Extension",
    isConnected: true,
    lastSynced: "2026-02-26T09:00:00Z",
    itemCount: 8,
    icon: "Globe",
  },
  {
    id: "7",
    type: "manual",
    name: "Manual Links",
    isConnected: true,
    lastSynced: "2026-02-26T09:10:00Z",
    itemCount: 5,
    icon: "Link",
  },
];
