import * as schema from "../schema";

it("exports every PostgreSQL table through the Phase 3 tenant expansion", () => {
  expect(Object.keys(schema).sort()).toEqual(
    [
      "agentActions",
      "accountDeletionTombstones",
      "accountDeletions",
      "accountExports",
      "aiSummaries",
      "approvalQueue",
      "auditLog",
      "authIdentities",
      "captureRequests",
      "captureTokens",
      "chatConversations",
      "chatMessages",
      "claimEvidence",
      "collectionItems",
      "collections",
      "connectorOAuthStates",
      "annotations",
      "contentChunks",
      "digestItems",
      "digestJobs",
      "digestRuns",
      "feedback",
      "itemEmbeddings",
      "intelligenceArtifacts",
      "intelligenceClaims",
      "invitations",
      "itemEvents",
      "itemContentVersions",
      "itemNotes",
      "items",
      "jobQueue",
      "knowledgeBackfillCheckpoints",
      "notifications",
      "oauthTokens",
      "operatorAuditEvents",
      "publisherQueue",
      "personalPreferences",
      "rateLimitWindows",
      "rawContent",
      "researchReports",
      "researchSuggestionSources",
      "researchSuggestions",
      "sessionMetadata",
      "usageCounters",
      "userEntitlements",
      "userQuotas",
      "userSettings",
      "users",
      "workflowRuns",
    ].sort()
  );
});

it("exposes relational metadata for critical capture tables", () => {
  expect(schema.captureRequests.id).toBeDefined();
  expect(schema.captureRequests.normalizedUrl).toBeDefined();
  expect(schema.captureTokens.tokenHash).toBeDefined();
  expect(schema.rateLimitWindows.windowStart).toBeDefined();
  expect(schema.rawContent.itemId).toBeDefined();
  expect(schema.items.readingProgress).toBeDefined();
  expect(schema.itemNotes.itemId).toBeDefined();
  expect(schema.annotations.contentVersion).toBeDefined();
  expect(schema.annotations.contentHash).toBeDefined();
  expect(schema.collectionItems.collectionId).toBeDefined();
  expect(schema.itemEvents.eventKey).toBeDefined();
  expect(schema.digestRuns.digestDate).toBeDefined();
  expect(schema.digestRuns.localDate).toBeDefined();
  expect(schema.digestRuns.selectionMetadata).toBeDefined();
  expect(schema.digestRuns.titleText).toBeDefined();
  expect(schema.digestItems.titleSnapshot).toBeDefined();
  expect(schema.personalPreferences.digestEnabled).toBeDefined();
  expect(schema.digestJobs.idempotencyKey).toBeDefined();
  expect(schema.itemContentVersions.contentHash).toBeDefined();
  expect(schema.contentChunks.searchVector).toBeDefined();
  expect(schema.contentChunks.embeddingStatus).toBeDefined();
  expect(schema.intelligenceArtifacts.supersedesArtifactId).toBeDefined();
  expect(schema.intelligenceClaims.claimHash).toBeDefined();
  expect(schema.claimEvidence.exactExcerpt).toBeDefined();
  expect(schema.knowledgeBackfillCheckpoints.jobKey).toBeDefined();
  expect(schema.users.id).toBeDefined();
  expect(schema.invitations.normalizedEmail).toBeDefined();
  expect(schema.accountExports.downloadExpiresAt).toBeDefined();
  expect(schema.accountDeletions.purgeAfter).toBeDefined();
  expect(schema.researchSuggestionSources.itemId).toBeDefined();
});
