import * as schema from "../schema";

it("exports every PostgreSQL table through Phase 2 intelligence", () => {
  expect(Object.keys(schema).sort()).toEqual(
    [
      "agentActions",
      "aiSummaries",
      "approvalQueue",
      "auditLog",
      "captureRequests",
      "captureTokens",
      "chatConversations",
      "chatMessages",
      "claimEvidence",
      "collectionItems",
      "collections",
      "annotations",
      "contentChunks",
      "digestItems",
      "digestRuns",
      "feedback",
      "itemEmbeddings",
      "intelligenceArtifacts",
      "intelligenceClaims",
      "itemEvents",
      "itemContentVersions",
      "itemNotes",
      "items",
      "jobQueue",
      "knowledgeBackfillCheckpoints",
      "notifications",
      "oauthTokens",
      "publisherQueue",
      "rateLimitWindows",
      "rawContent",
      "researchReports",
      "researchSuggestions",
      "userSettings",
      "workflowRuns",
    ].sort()
  );
});

it("exposes relational metadata for critical capture tables", () => {
  expect(schema.captureRequests.id).toBeDefined();
  expect(schema.captureRequests.normalizedUrl).toBeDefined();
  expect(schema.captureTokens.tokenHash).toBeDefined();
  expect(schema.rateLimitWindows.windowStart).toBeDefined();
  expect(schema.rawContent.itemId).toBeDefined();
  expect(schema.items.readingProgress).toBeDefined();
  expect(schema.itemNotes.itemId).toBeDefined();
  expect(schema.annotations.contentVersion).toBeDefined();
  expect(schema.annotations.contentHash).toBeDefined();
  expect(schema.collectionItems.collectionId).toBeDefined();
  expect(schema.itemEvents.eventKey).toBeDefined();
  expect(schema.digestRuns.digestDate).toBeDefined();
  expect(schema.itemContentVersions.contentHash).toBeDefined();
  expect(schema.contentChunks.searchVector).toBeDefined();
  expect(schema.contentChunks.embeddingStatus).toBeDefined();
  expect(schema.intelligenceArtifacts.supersedesArtifactId).toBeDefined();
  expect(schema.intelligenceClaims.claimHash).toBeDefined();
  expect(schema.claimEvidence.exactExcerpt).toBeDefined();
  expect(schema.knowledgeBackfillCheckpoints.jobKey).toBeDefined();
});
